parameters:
  param: []
  


steps:
  - ${{ each p in parameters.param }}:
    - script: 'echo ${{ lower( p ) }}'
    - task: Maven@3
      displayName: 'install ${{ p }}'
      inputs:
        mavenPomFile: '$(Build.SourcesDirectory)/${{ lower( p ) }}/pom.xml'
        mavenDirectory: '$(Build.SourcesDirectory)/${{ lower( p ) }}'
        goals: 'install'
        options: '-U    '
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '11'
        mavenVersionOption: 'Default'
        mavenOptions: '-Xmx3072m  $(MAVEN_OPTS)'
        mavenAuthenticateFeed: true
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
        checkStyleRunAnalysis: false # replaced by sonarqube
        pmdRunAnalysis: false  
        findBugsRunAnalysis: false  
        javadoc: false       
    - bash: |
        echo "##vso[task.setvariable variable=mySecretVal;issecret=false]ImRobert"
    - bash: |
        echo ------$(mySecretVal) ---------- 
    - bash: |
        echo ----${{ lower( p ) }}--- equal t1--------
      displayName: 'test condition: ${{ lower( p ) }} is eq t1 '
      condition: eq('${{ lower( p ) }}','t1') 
      continueOnError: true

    - bash: |
        echo ----${{ lower( p ) }}---not equal t1--------
      displayName: 'test condition: ${{ lower( p ) }} is not eq t1 '
      condition: ne('${{ lower( p ) }}','t1') 
      continueOnError: true